# Generated by Django 4.0 on 2022-01-04 14:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 4, 14, 10, 55, 546007, tzinfo=utc)),
        ),
    ]
